---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager 
summary: 'BlueXP permet aux experts IT et aux architectes cloud de gérer de manière centralisée leur infrastructure multicloud hybride à l"aide des solutions cloud NetApp.' 
---
= En savoir plus sur BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP (anciennement Cloud Manager) permet aux experts IT et aux architectes cloud de gérer de manière centralisée leur infrastructure multicloud hybride à l'aide des solutions cloud NetApp.



== Caractéristiques

BlueXP est une plateforme de gestion SaaS professionnelle qui vous permet de garder le contrôle de vos données, où qu'elles se trouvent.

* Configuration et utilisation https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] pour une gestion efficace des données multiprotocole sur l'ensemble des clouds.
* Configurez et utilisez les services cloud de stockage de fichiers :
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX pour ONTAP"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]


* Détection et gestion https://bluexp.netapp.com/netapp-on-premises["le stockage sur site"^]
+
** Systèmes E-Series
** Clusters ONTAP
** Systèmes StorageGRID


* Utilisez les services BlueXP pour la mobilité, la protection des données, l'analyse et le contrôle des données :
+
** https://bluexp.netapp.com/cloud-backup["La sauvegarde dans le cloud"^]
** https://bluexp.netapp.com/netapp-cloud-data-sense["Sens des données cloud"^]
** https://bluexp.netapp.com/cloud-sync-service["Cloud Sync"^]
** https://bluexp.netapp.com/cloud-tiering["Tiering dans le cloud"^]
** https://bluexp.netapp.com/digital-advisor["Conseiller digital"^]
** https://bluexp.netapp.com/global-file-cache["Cache global de fichiers"^]
** https://bluexp.netapp.com/k8s["Kubernetes"^]
** https://bluexp.netapp.com/ransomware-protection["Protection contre les ransomwares"^]
** https://bluexp.netapp.com/replication["La réplication"^]




https://cloud.netapp.com/cloud-manager["En savoir plus sur BlueXP"^]



== Fournisseurs cloud pris en charge

BlueXP vous permet de gérer le stockage cloud et d'utiliser les services cloud dans Amazon Web Services, Microsoft Azure et Google Cloud.



== Le coût

Le prix de BlueXP dépend des services que vous prévoyez d'utiliser. https://bluexp.netapp.com/pricing["En savoir plus sur les tarifs BlueXP"^].



== Fonctionnement de BlueXP

BlueXP comprend une interface SaaS intégrée au site Web BlueXP et des connecteurs qui gèrent Cloud Volumes ONTAP et d'autres services Cloud.



=== Services à la demande

BlueXP est accessible via un https://console.bluexp.netapp.com["Interface utilisateur SaaS"^] Et les API. Cette expérience SaaS vous permet d'accéder automatiquement aux toutes dernières fonctionnalités dès leur sortie et de basculer facilement d'un compte à l'autre de vos connecteurs et de vos comptes NetApp.


TIP: Si vous travaillez dans un environnement où l'accès Internet sortant n'est pas disponible, vous pouvez installer le logiciel Connector dans cet environnement et accéder à l'interface utilisateur locale disponible sur le connecteur. link:concept-connectors.html["En savoir plus sur les connecteurs"].



=== Site Web BlueXP

https://cloud.netapp.com["Le site Web BlueXP"^] cette solution est centralisée pour l'accès et la gestion https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["Services clouds NetApp"^]. Avec l'authentification utilisateur centralisée, vous pouvez utiliser le même ensemble d'informations d'identification pour accéder à BlueXP et à d'autres services cloud comme Cloud Insights.



=== Compte NetApp

Lorsque vous vous connectez à BlueXP pour la première fois, vous êtes invité à créer un _compte NetApp_. Ce compte fournit la colocation et vous permet d'organiser les utilisateurs et les ressources dans des _espaces de travail_ isolés.



=== Connecteurs

Dans la plupart des cas, un administrateur de compte BlueXP devra déployer un _Connector_ dans votre réseau cloud ou sur site. BlueXP peut ainsi gérer les ressources et les processus au sein de votre environnement de cloud public.

link:concept-connectors.html["En savoir plus sur le moment où les connecteurs sont nécessaires et leur fonctionnement"].



== Certification SOC 2 Type 2

Nous avons étudié BlueXP, Cloud Sync, Cloud Tiering, Cloud Data Sense et Cloud Backup (plateforme BlueXP), et confirmé que leur cabinet d'experts-comptables indépendant a réussi à générer des rapports SOC 2 de type 2 d'après les critères des services de confiance applicables.

https://www.netapp.com/company/trust-center/compliance/soc-2/["Consultez les rapports SOC 2 de NetApp"^]
