---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager 
summary: 'BlueXP permet aux experts IT et aux architectes cloud de gérer de manière centralisée leur infrastructure multicloud hybride à l"aide des solutions cloud NetApp.' 
---
= En savoir plus sur BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP (anciennement Cloud Manager) permet aux experts IT et aux architectes cloud de gérer de manière centralisée leur infrastructure multicloud hybride à l'aide des solutions cloud NetApp.



== Caractéristiques

BlueXP est une plateforme de gestion SaaS professionnelle qui vous permet de garder le contrôle de vos données, où qu'elles se trouvent.

* Configuration et utilisation https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] pour une gestion efficace des données multiprotocole sur l'ensemble des clouds.
* Configuration et utilisation des services de stockage de fichiers :
+
** https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://cloud.netapp.com/fsx-for-ontap["Amazon FSX pour ONTAP"^]
** https://cloud.netapp.com/cloud-volumes-service-for-aws["Cloud Volumes Service pour AWS"^]
** https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]


* Découvrez et gérez les clusters ONTAP sur site en créant des volumes, en sauvegardant dans le cloud, en répliquant les données dans l'ensemble de votre cloud hybride et en effectuant le Tiering des données inactives dans le cloud.
* Profiter de services clouds intégrés, tels que :
+
** https://cloud.netapp.com/cloud-compliance["Sens des données cloud"^]
** https://cloud.netapp.com/cloud-insights["Cloud Insights"^]
** https://cloud.netapp.com/cloud-backup-service["La sauvegarde dans le cloud"^]




https://cloud.netapp.com/cloud-manager["En savoir plus sur BlueXP"^].



== Fournisseurs de stockage objet pris en charge

BlueXP vous permet de gérer le stockage cloud et d'utiliser les services cloud dans Amazon Web Services, Microsoft Azure et Google Cloud.



== Le coût

BlueXP logiciel est gratuit auprès de NetApp.

Pour la plupart des tâches, BlueXP vous invite à déployer un connecteur dans votre réseau cloud, ce qui entraîne des frais pour l'instance de calcul et le stockage associé de votre fournisseur cloud. Vous avez la possibilité d'exécuter le logiciel de connecteur sur votre site.

link:reference-connector-default-config.html["En savoir plus sur la configuration par défaut du connecteur"].



== Fonctionnement de BlueXP

BlueXP comprend une interface SaaS intégrée au site Web BlueXP et des connecteurs qui gèrent Cloud Volumes ONTAP et d'autres services Cloud.



=== Services à la demande

BlueXP est accessible via un https://cloudmanager.netapp.com["Interface utilisateur SaaS"^] Et les API. Cette expérience SaaS vous permet d'accéder automatiquement aux toutes dernières fonctionnalités dès leur sortie et de basculer facilement d'un compte à l'autre de vos connecteurs et de vos comptes NetApp.


TIP: Si vous travaillez dans un environnement où l'accès Internet sortant n'est pas disponible, vous pouvez installer le logiciel Connector dans cet environnement et accéder à l'interface utilisateur locale disponible sur le connecteur. link:concept-connectors.html["En savoir plus sur les connecteurs"].



=== Site Web BlueXP

https://cloud.netapp.com["Le site Web BlueXP"^] cette solution est centralisée pour l'accès et la gestion https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["Services clouds NetApp"^]. Avec l'authentification utilisateur centralisée, vous pouvez utiliser le même ensemble d'informations d'identification pour accéder à BlueXP et à d'autres services cloud comme Cloud Insights.



=== Compte NetApp

Lorsque vous vous connectez à BlueXP pour la première fois, vous êtes invité à créer un _compte NetApp_. Ce compte fournit la colocation et vous permet d'organiser les utilisateurs et les ressources dans des _espaces de travail_ isolés.



=== Connecteurs

Dans la plupart des cas, un administrateur de compte BlueXP devra déployer un _Connector_ dans votre réseau cloud ou sur site. BlueXP peut ainsi gérer les ressources et les processus au sein de votre environnement de cloud public.

link:concept-connectors.html["En savoir plus sur le moment où les connecteurs sont nécessaires et leur fonctionnement"].



== Certification SOC 2 Type 2

Nous avons étudié BlueXP, Cloud Sync, Cloud Tiering, Cloud Data Sense et Cloud Backup (plateforme BlueXP), et confirmé que leur cabinet d'experts-comptables indépendant a réussi à générer des rapports SOC 2 de type 2 d'après les critères des services de confiance applicables.

https://www.netapp.com/company/trust-center/compliance/soc-2/["Consultez les rapports SOC 2 de NetApp"^]
